export const Unites = [
    { uid: 1, nom: 'Zanfleuron', sexe: 'homme' },
    { uid: 2, nom: 'Manloud', sexe: 'homme' },
    { uid: 5, nom: 'LaNeuvaz', sexe: 'homme' },
    { uid: 6, nom: 'Chandelard', sexe: 'homme' },
    { uid: 7, nom: 'Berisal', sexe: 'homme' },
    { uid: 8, nom: 'Montfort', sexe: 'homme' },
    { uid: 9, nom: 'Lovegno', sexe: 'homme' },
    { uid: 10, nom: 'Solalex', sexe: 'femme' },
    { uid: 11, nom: 'Grammont', sexe: 'femme' },
    { uid: 12, nom: 'Armina', sexe: 'femme' },
    { uid: 13, nom: 'Santis', sexe: 'femme' },
    { uid: 20, nom: 'Montd\'Or', sexe: 'homme' },
    { uid: 21, nom: 'Clairière', sexe: 'homme' },
    { uid: 22, nom: 'Cabéru', sexe: 'femme' },
    { uid: 23, nom: 'Chenaulaz', sexe: 'femme' },
];

export const SousUnites = [
    { sid: 1, uid: 1, nom: 'Bouquetins' },
    { sid: 2, uid: 1, nom: 'Lynx' },
    { sid: 3, uid: 1, nom: 'Aigles' },
    { sid: 4, uid: 1, nom: 'Castors' },
    { sid: 5, uid: 2, nom: 'Loups' },
    { sid: 6, uid: 2, nom: 'Hermines' },
    { sid: 7, uid: 2, nom: 'Eperviers' },
    { sid: 8, uid: 2, nom: 'Ours' },
    { sid: 9, uid: 2, nom: 'Taureaux' },
    { sid: 10, uid: 5, nom: 'Antilopes' },
    { sid: 11, uid: 5, nom: 'Cigognes' },
    { sid: 12, uid: 5, nom: 'Hérons' },
    { sid: 13, uid: 5, nom: 'Renards' },
    { sid: 14, uid: 5, nom: 'Loutres' },
    { sid: 15, uid: 5, nom: 'Chauves-souris' },
    { sid: 16, uid: 6, nom: 'Rennes' },
    { sid: 17, uid: 6, nom: 'Marmottes' },
    { sid: 18, uid: 6, nom: 'Poussins-Coqs' },
    { sid: 19, uid: 6, nom: 'Cygnes' },
    { sid: 20, uid: 6, nom: 'Yacks' },
    { sid: 21, uid: 7, nom: 'Panthères' },
    { sid: 22, uid: 7, nom: 'Koalas' },
    { sid: 23, uid: 7, nom: 'Cerfs' },
    { sid: 24, uid: 7, nom: 'Faucons' },
    { sid: 25, uid: 7, nom: 'Léopards' },
    { sid: 26, uid: 8, nom: 'Surcouf' },
    { sid: 27, uid: 8, nom: 'Jean-Bart' },
    { sid: 28, uid: 8, nom: 'Frégate' },
    { sid: 29, uid: 8, nom: 'Galion' },
    { sid: 30, uid: 9, nom: 'Phénix' },
    { sid: 31, uid: 9, nom: 'Cobras' },
    { sid: 32, uid: 9, nom: 'Tigres' },
    { sid: 33, uid: 10, nom: 'Hirondelles' },
    { sid: 34, uid: 10, nom: 'Ratons-Laveurs' },
    { sid: 35, uid: 10, nom: 'Goélands' },
    { sid: 36, uid: 10, nom: 'Pandas' },
    { sid: 37, uid: 10, nom: 'Gazelles' },
    { sid: 38, uid: 11, nom: 'Licornes' },
    { sid: 39, uid: 11, nom: 'Fennecs' },
    { sid: 40, uid: 11, nom: 'Okapis' },
    { sid: 41, uid: 11, nom: 'Kangourous' },
    { sid: 42, uid: 11, nom: 'Chevreuils' },
    { sid: 43, uid: 12, nom: 'Impalas' },
    { sid: 44, uid: 12, nom: 'Mangoustes' },
    { sid: 45, uid: 12, nom: 'Coyotes' },
    { sid: 46, uid: 12, nom: 'Caméléons' },
    { sid: 47, uid: 13, nom: 'Oryx' },
    { sid: 48, uid: 13, nom: 'Condors' },
    { sid: 49, uid: 13, nom: 'Irbis' },
    { sid: 101, uid: 20, nom: 'Panthères(lvtx)' },
    { sid: 102, uid: 20, nom: 'Koalas(lvtx)' },
    { sid: 103, uid: 20, nom: 'Renards' },
    { sid: 104, uid: 20, nom: 'Kangourous' },
    { sid: 105, uid: 21, nom: 'Ours(lvtx)' },
    { sid: 106, uid: 21, nom: 'Dauphins' },
    { sid: 107, uid: 21, nom: 'Chevaux' },
    { sid: 108, uid: 22, nom: 'Panthères(lvttes)' },
    { sid: 109, uid: 22, nom: 'Chouettes' },
    { sid: 110, uid: 22, nom: 'Ours(lvttes)' },
    { sid: 111, uid: 22, nom: 'Elephants' },
    { sid: 112, uid: 23, nom: 'Opossums' },
    { sid: 113, uid: 23, nom: 'Koalas(lvttes)' },
    { sid: 114, uid: 23, nom: 'Wombats' },
    { sid: 115, uid: 23, nom: 'Quokkas' },
];

export const getUnite = uid => Unites.find(u => u.uid === uid);
export const getSousUnite = sid => SousUnites.find(s => s.sid === sid);
